include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.gen.dart
    - lib/**/*.freezed.dart
linter:
  rules:
    public_member_api_docs: false
